target-version = "py314"
line-length = 100
src = ["apps", "libs"]

[lint]
select = ["E", "F", "I", "B", "UP", "N", "ASYNC", "RUF"]
ignore = ["B008", "E501", "RUF012"]

[format]
quote-style = "double"
indent-style = "space"
